In [2]:
!PiP install numpy

In [3]:
import numpy as np

In [9]:
# axis= 0 is used for row and axis= 1 is used for column
a=np.array([[1,2],[7,8]])
b=np.array([[3,4],[5,6]])
z=np.concatenate((a,b),axis=0)
z

array([[1, 2],
       [7, 8],
       [3, 4],
       [5, 6]])

In [10]:
#axis= 1 is used for column
a=np.array([[1,2],[7,8]])
b=np.array([[3,4],[5,6]])
z=np.concatenate((a,b),axis=1)
z

array([[1, 2, 3, 4],
       [7, 8, 5, 6]])

### reshape

In [16]:
a=z.reshape(4,2)
a

array([[1, 2],
       [3, 4],
       [7, 8],
       [5, 6]])

### Indexing and slicing

In [17]:
###basic array opration

data =np.array([1,2])
ones_arr=np.ones(2,dtype=int)
x= data + ones_arr
x

array([2, 3])

In [18]:
y= data - ones_arr
z=data*ones_arr
a=data /ones_arr
print(y,z,a)

[0 1] [1 2] [1. 2.]


### More useful array opration

In [19]:
### minimum,maximum,sum,mean,product,standard deviation and more

In [ ]:
'''
mean = sum of element / total number of element
mode= highest frequency is mode [repedated for many time]
medium= set in  the ascending order[n/2] if'n' is odd we do [n+1/2] and for even [n/2]
the avarage of the n/2 will bw medium
